# set base image (host OS)
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3 python3-dev python3-pip python3-venv
RUN apt-get update && apt-get install -y tcpdump nano nethogs iotop nmon nmap

# set the working directory in the container
WORKDIR /code

# install dependencies
RUN pip install neo4j && pip install uvicorn && pip install fastapi && pip install pandas && pip install pronto && pip install owlready2
RUN mkdir /code/src && mkdir /code/owl_file && mkdir /code/logs

WORKDIR /code/src
CMD [ "uvicorn","main:app", "--host=0.0.0.0", "--reload"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]