version: '3'

# todo auth
services:
      ontoservice:
            build:
                  context : ./ontoservice/
                  args:
                  - NODE_ENV=local
                  dockerfile: ./dockerfile
            ports:
                  - 8000:8000
            volumes:
                  - ../src/:/code/src/
      myneo:
            build:
                  context : ./docker_neo/
                  args:
                  - NODE_ENV=local
                  dockerfile: ./dockerfile
            ports:
                  - 7474:7474
                  - 7687:7687
            volumes:
                  - ./docker_neo/conf/neo4j.conf:/var/lib/neo4j/conf/neo4j.conf






              # docker exec -it <mycontainer> bash