FROM neo4j:5.7.0

RUN apt-get update && apt-get install -y wget curl  && rm -rf /var/lib/apt/lists/*
RUN cd /var/lib/neo4j/plugins/ && wget https://github.com/neo4j-labs/neosemantics/releases/download/5.7.0.0/neosemantics-5.7.0.0.jar
#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["/var/lib/neo4j/bin/neo4j", "console", "--verbose"]

